### ISSUE TITLE
Add custom named header columns

### ISSUE THREAD

**Issue by StoneyCreeker** [micz/ColumnsWizard#19]
I am creating exim spam filter rules for my small mail server and have written my code to add a new header to the end of possible spam message headers called "SpamRule" . I can see it in TB in the headers view and it tells me which rule flagged the message as spam to edit it for false-positives. It would be nice if I could have a column for this header to see which ones are doing most of the filtering. Can this be done with ColumnsWizard or maybe with a new feature?

**Comment by micz** [comment]
From version 5.0 you can add a custom column directly from the addon preference panel.
The StoneyCreeker branch has been deleted.

**Comment by StoneyCreeker** [comment]
I updated to 5.0 and the supplied custom columns work fine.
But when I try to add new it does not work.
I go to "New..."
Under ID I add MySpamRules
Under Mail Header I add SpamRule
Under Column Name I add SpamRule
Under Tooltip I add sort by SpamRule
I check the "Enabled" checkbox

When I click "OK" nothing happens.

**Comment by micz** [comment]
My bad, I left a breakpoint I added fro a test and not removed it before the release.
I'm releasing version 5.0.1.

**Comment by StoneyCreeker** [comment]
Works perfect!!!!

Thanks Mic

My donation is on it's way...



-----Original Message-----

**Comment by micz** [comment]
I'm happy it worked!
Thank you!
