### ISSUE TITLE
Mail Header Editor not cross compatible

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#53]
I cannot add anything from "CW Header Edit -> Mycolumn -> Mail Header Editor" for emails that have been sent from SquirrelMail (gandi.net tested).

**Comment by micz** [comment]
May you tell me what is the behaviour in this case?
There is an error message? It seems to work right, but it does not modify the header?
Which is the account type? (IMAP, POP3)
Thanks.

**Comment by flyingzebras** [comment]
"There is an error message?": No

"It seems to work right, but it does not modify the header?": Yes

"Which is the account type? (IMAP, POP3)": IMAP

**Comment by micz** [comment]
I'm sorry but I need to see the header information of one of those messages.
If you agree to show that to me, do not publish it here, but send it to m@micz.it.
Thanks.

**Comment by flyingzebras** [comment]
I could edit it now, this is weird as I still use CW version 6.0. I keep you updated if I encounter this issue in the future.
