### ISSUE TITLE
License conflict between CC BY-NC and GPLv3

### ISSUE THREAD

**Issue by joshuagay** [micz/ColumnsWizard#57]
While reviewing the entry for [ColumnsWizard](http://directory.fsf.org/wiki/ColumnsWizard) as part of my volunteer work for the FSF's Free Software Directory, I noticed that the license for ColumnsWizard states  "ColumnsWizard is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc/4.0/" and that it also goes on to state that it is licensed under the terms of the GNU GPL. However, CC BY-NC and GPLv3 are not compatible licenses. If you are the copyright holder and are able to do so, I recommend removing the license statement which says that it is licensed under CC BY-NC.

**Comment by micz** [comment]
I fixed the problem in commit https://github.com/micz/ColumnsWizard/commit/71a3aa8cac4a354960ae580245253a7fb97e746f.
I'm going to submit version 6.0.4 for release.
Thank you.

**Comment by micz** [comment]
Version 6.0.4 has been reviewed and released.
