### ISSUE TITLE
New custom column has blank content

### ISSUE THREAD

**Issue by tyrogidome** [micz/ColumnsWizard#58]
Among the headers on each inbound Gmail message is "Delivered-To" which
is never empty. I used Column Wizard to create a custom column that should
display the contents of this field on my Gmail account, but the field is blank
for all of the 2600 messages in the account.

Did I do something wrong?

Is this a bug?

How might I fix this?

**Comment by micz** [comment]
Thunderbird shows custom columns only for mails received after the new column setup.
You could try to repair the folder (losing any folder properties like columns setup and sorting column and order), but in some Thunderbird versions it doesn't work.

**Comment by tyrogidome** [comment]
You were right: it only shows the new column's content for new messages.
Also, I had to restart Thunderbird for it to work. Looks good so far. Thanks.
You can close thread.

**Comment by micz** [comment]
Thank you for your report.
