### ISSUE TITLE
Cannot remove text from emails once added

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#59]
Steps to reproduce:
* ColumnsWizard -> Custom Columns -> New -> Foo
* Show the new column in say Inbox.
* Select a mail -> Context -> CV Header Edit -> Foo -> Enter "Bar"
* Repeat the previous step but remove "Bar" this time. It won't work, "Bar" will still be stated.

**Comment by micz** [comment]
I'll add a "Empty header" menu item to clear a previously filled custom header.

**Comment by davidhedlund** [comment]
@micz I'm happy to hear that. But why not make it possible to empty them as in the example in provided?

**Comment by davidhedlund** [comment]
@micz Thank you for adding this to the 6.1 milestone.

**Comment by davidhedlund** [comment]
Thanks.

**Comment by micz** [comment]
You can try new feature this in version 6.1alpha8.

**Comment by davidhedlund** [comment]
I'm stuck on this step
> Select a mail -> Context -> CV Header Edit -> Foo -> Enter "Bar"
I cannot add any text at all now.

**Comment by micz** [comment]
May you post a screenshot to explain the issue you're facing?
Thank you.

**Comment by davidhedlund** [comment]
I updated my comment https://github.com/micz/ColumnsWizard/issues/59#issuecomment-368733814

You can delete your comment https://github.com/micz/ColumnsWizard/issues/59#issuecomment-368758462

**Comment by micz** [comment]
When you are trying to remove the text do you see this check?

![image](https://user-images.githubusercontent.com/61795/36758285-4c2222dc-1c14-11e8-9f15-82c32f3167e7.png)

May you post your logs with the debug system active?
Thank you.

**Comment by davidhedlund** [comment]
> When you are trying to remove the text do you see this check?

Unfortunately not.

> May you post your logs with the debug system active?

icedove -debug didn't output anything. What should I do instead?

**Comment by micz** [comment]
On Thunderbird you should press CTRL+SHIFT+J.
To activate the debug system, please read here: https://github.com/micz/ColumnsWizard/issues/65#issuecomment-366079293
Thank you.

**Comment by davidhedlund** [comment]
Thanks. The debug log didn't show anything because nothing happened. The progress bar didn't show up as I described in https://github.com/micz/ColumnsWizard/issues/59#issuecomment-368733814

**Comment by micz** [comment]
Have you activated the debug system? Log info are printed even when the menu is opened.
Thank you.

**Comment by davidhedlund** [comment]
> Have you activated the debug system?

Yes

> Advanced -> Activate the bug system.

Then I hit Ctrl+Shift+F2

Then I tried to delete text:
* CV Header Edit -> Foo -> tried to remove "Bar"


But I don't even see the menu you mentioned in https://github.com/micz/ColumnsWizard/issues/59#issuecomment-369046675

**Comment by micz** [comment]
I meant the debug system of my addon from the preference panel.

![image](https://user-images.githubusercontent.com/61795/36760275-7a43730e-1c1a-11e8-93fe-1fb464abda4d.png)


The menu I posted is for the test environment I use, where I added an editable custom column named "test_Name3", with three "fixed list" values "prova1, prova2, prova3".

**Comment by davidhedlund** [comment]
I deleted my profile directory. Can you please provide me **exact** steps from scratch?

**Comment by micz** [comment]
**1. Add a fixed list editable custom column**
* ID: fltest
* Mail Header: fltest
* Column Name: FL Test
* Tooltip: Fixed List Test
* Editable: Check "This mail message header can be manually modified."

**2. Editing TAB**
* Header Type: choose Fixed List
* In the text box insert these three lines:
  * Apple
  * Orange
  * Banana
  
**3. Save the custom column**
**4. Show the custom column in a folder.**
**5. Right click on a mail message and choose a value from the menu, as shown below. The value is set and shown in the column.**

![image](https://user-images.githubusercontent.com/61795/36816819-520fd916-1cdf-11e8-8cf6-461a07a29cbe.png)

**6. Right click on a mail message and choose again the same value (that has a check near the label). The value is removed.**

![image](https://user-images.githubusercontent.com/61795/36816862-75dd43f6-1cdf-11e8-93a6-9aff0f773015.png)

**Comment by davidhedlund** [comment]
Thank you for taking your time with screenshots and everything. I appreciate that.

* Numbers: It's possible to add **but not** to remove text
* Free text: It's possible to add **but not** to remove text
* Fixed list: It's possible to add **and** remove text

**Comment by micz** [comment]
You can try this fix in version 6.1alpha9.

**Comment by davidhedlund** [comment]
Finally fixed. Just to verify:
* Numbers: It's possible to add **and** remove text
* Free text: It's possible to add **and** remove text
* Fixed list: It's possible to add **and** remove text

Thank you very much.
