### ISSUE TITLE
Mail Header capitals ignored

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#60]
Client: Thunderbird 52.2.1(GNU/Linux 64 bit) -- Icedove 38.8.0 was used to capture the screenshots but the bugs are identical in Thunderbird.
ColumnsWizard version: 6.0.4

# Mail Header capitals ignored

![screenshot from 2017-07-18 15 52 41](https://user-images.githubusercontent.com/6416073/28320755-ab883cdc-6bd1-11e7-9573-9028c9b74df7.png)

![screenshot from 2017-07-18 16 07 10](https://user-images.githubusercontent.com/6416073/28321297-318c09de-6bd3-11e7-91e8-dd81b4ab127a.png)

As you can see, the Mail Header changed "Test" as seen in the first screenshot to "test" in the second screenshot.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
![screenshot from 2017-07-18 15 52 41](https://user-images.githubusercontent.com/6416073/28320755-ab883cdc-6bd1-11e7-9573-9028c9b74df7.png)

**Comment by davidhedlund** [comment]
# Mail Header capitals ignored

![screenshot from 2017-07-18 15 52 41](https://user-images.githubusercontent.com/6416073/28320755-ab883cdc-6bd1-11e7-9573-9028c9b74df7.png)

![screenshot from 2017-07-18 16 07 10](https://user-images.githubusercontent.com/6416073/28321297-318c09de-6bd3-11e7-91e8-dd81b4ab127a.png)

As you can see, the Mail Header changed "Test" as seen in the first screenshot to "test" in the second screenshot.

# "Enable mail headers editing." rule broken

![screenshot from 2017-07-18 16 15 37](https://user-images.githubusercontent.com/6416073/28321766-5ce66416-6bd4-11e7-8cb9-11003029b44a.png)

Its not turned on automatically. Not when I Close the window and re-open it, or even if I restart Icedove.

# Columns not visible for editing

![screenshot from 2017-07-18 16 17 53](https://user-images.githubusercontent.com/6416073/28321859-abf651a6-6bd4-11e7-9560-f5621f46c654.png)

Even if I check "Enable mail headers editing." I don't see the column in "CW Header Edit", its empty.

**Comment by davidhedlund** [comment]
@micz Can you please have a look on these issues?

CW is broken, I cannot use it at all right now.

**Comment by davidhedlund** [comment]
I'm using

Client: Icedove 38.8.0 (GNU/Linux)
ColumnsWizard version: 6.0.4

**Comment by davidhedlund** [comment]
@micz Please label this issue "Bug".

**Comment by davidhedlund** [comment]
These bugs are also valid in the latest version of Thunderbird (52.2.1).

**Comment by micz** [comment]
Please try version 6.1alpha2 from the beta channel. Thank you.

**Comment by davidhedlund** [comment]
Sorry, I didn't find the link for 6.1alpha2, what is it?

**Comment by micz** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/columnswizard/versions/beta

**Comment by davidhedlund** [comment]
I can verify that the new version works. Let's close this issue when you have release the stable version.

Thank you.

**Comment by micz** [comment]
Fixed in version 6.1.
