### ISSUE TITLE
Convert ColumnsWizard to a WebExtension

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#61]
https://addons.mozilla.org/api/v3/addons/addon/columnswizard/feature_compatibility/ says
> {"e10s":"unknown"}

ColumnsWizard is the absolutely best add-on for Thunderbird and Icedove that I've ever used. Can you please make it a web extension if you got time for it?

Not havint CW in the future will impact the infrastructure of the way I handle bug emails etc.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by yfdyh000** [comment]
Thunderbird will not have and be WebExtension so far.

**Comment by davidhedlund** [comment]
@yfdyh000 

> Thunderbird will not have and be WebExtension so far.

Can you please proof read that?

**Comment by yfdyh000** [comment]
https://wiki.mozilla.org/Add-ons/2017#Firefox_53

**Comment by davidhedlund** [comment]
@yfdyh000 Thank you for the link. How will this affect CW?

**Comment by yfdyh000** [comment]
> https://wiki.mozilla.org/Add-ons/2017#Firefox_53
>Thunderbird and Seamonkey extensions will be unaffected.

> Can you please make it a web extension if you got time for it?

I have not heard that Thunderbird is implementing the WebExtension infrastructure.

**Comment by davidhedlund** [comment]
@yfdyh000 Oh, I get it now. Thank you for explaining this to me.

But would you make CW a web extension if Thunderbird implemented the WebExtension infrastructure?

**Comment by yfdyh000** [comment]
> But would you make CW a web extension if Thunderbird implemented the WebExtension infrastructure?

It is very far away, you should waiting for have a draft at least.

Also, I don't works on this project.

**Comment by davidhedlund** [comment]
@yfdyh000 Ok.

**Comment by micz** [comment]
As long as I know there is no idea on moving web extension also to Thunderbird.
We need to wait for more info on this matter before discussing on how to port any extension to the new technology.

**Comment by micz** [comment]
See #66.

**Comment by davidhedlund** [comment]
I don't know why you opened an identical issue for this. Can you please explain?

**Comment by micz** [comment]
Because Thunderbird is not going to implement WebExtensions, but is only asking developers to add some modifications to their addons to be compatible to Thunderbird 57+, as described here: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

**Comment by davidhedlund** [comment]
[Add support for WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1396172)

**Comment by davidhedlund** [comment]
With the release of Thunderbird 68 in August 2019 it now only supports WebExtension addons. - https://www.thunderbird.net/en-US/thunderbird/68.0/releasenotes/

**Comment by davidhedlund** [comment]
Can you please re-open this issue @micz ?
