### ISSUE TITLE
Merge "Advanced" to "General", and enable "This mail message header can be manually modified."

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#62]
![screenshot from 2017-07-30 18 03 44](https://user-images.githubusercontent.com/6416073/28754989-7402a3ae-7551-11e7-87f6-42975824246c.png)

![screenshot from 2017-07-30 17 58 15](https://user-images.githubusercontent.com/6416073/28754972-deffd164-7550-11e7-834d-243cfdacffef.png)

* Its hard to overview that this must be enabled when its located in its own tab, I suggest that you merge the settings in "Advanced" to "General".
* CW cannot edit the columns as long as the its not enabled.

**Comment by micz** [comment]
Merging the two tabs it's not a viable option, since the window would become too big.
What if I add the checkbox on the general tab and rename the advanced tab to something like "Editing"?
If a user enables the checkbox but do not use the advanced tab, he could edit the header as free text.
I could implement this in version 6.1.
Thank you.

**Comment by davidhedlund** [comment]
>  What if I add the checkbox on the general tab and rename the advanced tab to something like "Editing"?

I like that idea.

**Comment by micz** [comment]
Ok, I'll add this on 6.1.

**Comment by davidhedlund** [comment]
You have almost fixed all issues that I've submitted. I must confess that I'm impressed about your productivity.

**Comment by micz** [comment]
It took a long time, but I hope to release 6.1 soon.
This a free-time project, and as you've seen, sometimes there is not enough free-time.
Thank you for your long time commitment to this addon.

**Comment by micz** [comment]
You can try new feature this in version 6.1alpha8.

**Comment by davidhedlund** [comment]
Tried it.

* Can you please enable this by default so columns can be edited?:

> This mail message header can be manually modified.

Most new users of your add-on won't have any clue that this option has to be enabled for them to edit columns.

**Comment by micz** [comment]
Editing a mail header it's not a common task. Enable it for non tech users could be dangerous.
I think that a user that knows what a mail header is, will find how to enable it.

**Comment by davidhedlund** [comment]
> Editing a mail header it's not a common task.

Isn't this the purpose with your add-on?

**Comment by micz** [comment]
I created this addon at the beginning to set a default columns layout for new folders. Than people asked for new features, like new columns on custom mail headers or (you ;-) ) mail header editing capability.
I added those features because I felt that they were useful for the purpose of this addon.

**Comment by davidhedlund** [comment]
> Than people asked for new features, like new columns on custom mail headers or (you ;-) )

Ah, now I remember. You are right. I'd just like more people to use this feature and to do that some sort of hint should be added.
