### ISSUE TITLE
Make the "Column name" fully visible

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#63]
![screenshot from 2017-07-30 18 03 44](https://user-images.githubusercontent.com/6416073/28754989-7402a3ae-7551-11e7-87f6-42975824246c.png)
The "Column name" field is not fully visible.

**Comment by micz** [comment]
Please try version 6.1alpha2 from the beta channel. Thank you.

**Comment by davidhedlund** [comment]
This is actually even worse in the beta release, see the screenshot. I filled the character "A" in every field just to show how the visibility differ in each field.

![screenshot from 2018-02-07 04 27 13](https://user-images.githubusercontent.com/6416073/35897091-cb17ad38-0bbf-11e8-815f-6423c9030e2d.png)

**Comment by micz** [comment]
Please try version 6.1alpha3 from here: https://addons.mozilla.org/it/thunderbird/addon/columnswizard/versions/beta

**Comment by davidhedlund** [comment]
That did the trick!

![screenshot from 2018-02-22 01 03 25](https://user-images.githubusercontent.com/6416073/36512786-467fc3c2-176c-11e8-8387-800772fe93fb.png)

**Comment by micz** [comment]
Fixed in 6.1.
Thank you.

**Comment by davidhedlund** [comment]
Dito.
