### ISSUE TITLE
Show CW custom columns text if you configure CW after you have added email accounts

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#64]
CW text in custom columns will show up properly if you:
1) Start a fresh profile in Thunderbird.
2) Configure ColumnsWizard.
3) Add email accounts.

but not if you:
1) Start a fresh profile in Thunderbird.
3) Add email accounts.
2) Configure ColumnsWizard.

**Comment by davidhedlund** [comment]
Please warn users about this step if CW is unable to do something about it.

**Comment by davidhedlund** [comment]
CW text in custom columns will show up properly if you:
1) Start a fresh profile in Thunderbird.
2) Configure ColumnsWizard.
3) Add email accounts.

but not if you:
1) Start a fresh profile in Thunderbird.
3) Add email accounts.
2) Configure ColumnsWizard.

**Comment by micz** [comment]
If I have correctly understood, this is not a CW problem. If you add the emails to Thunderbird and after that add a new header to be shown in a column, you need to force Thunderbird to rescan that folder, using the repair folder command, to add the new header to its internal database.
Feel free to open again this issue if this not correct.

**Comment by davidhedlund** [comment]
I'd prefer CW to automatically ask with a popup "You re-scan that folders for CW headers to show up in your new account: OK, Cancel"

What do you think about it?
