### ISSUE TITLE
Thunderbird 57+ compatibility

### ISSUE THREAD

**Issue by micz** [micz/ColumnsWizard#66]
Add Thunderbird 57+ compatibility.
See https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

**Comment by micz** [comment]
Working on https://github.com/micz/ColumnsWizard/tree/th59

**Comment by micz** [comment]
Fixed in https://github.com/micz/ColumnsWizard/commit/0fb401d07350b4c6ba73eabea527d8ee7240e364.

**Comment by davidhedlund** [comment]
You might be interested in a issue I started 5 months ago: [Add support for WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1396172)

**Comment by micz** [comment]
See my comment here: https://github.com/micz/ColumnsWizard/issues/61#issuecomment-364016910
