### ISSUE TITLE
not working with TB 52.6.0 on Mac OSX HighSierra 10.13.3

### ISSUE THREAD

**Issue by FranzMeyer** [micz/ColumnsWizard#67]
i have installed the extension 6.0.4 (downloaded the XPI file, and install manually wtih the add-on manager), re-ordered the columns as i wanted, like Correspondant before subject, and then i save it , and apply it to my inbox, and nothing happen...
Thanks for considering and helping.
Franz

**Comment by micz** [comment]
Dear Franz,

may you open the error console with CRTL+SHIFT+J, then do again what you described and send me the log to m@micz.it?

Thank you.

**Comment by FranzMeyer** [comment]
hi,

thanks for your quick reply.

It seems the CTRL+SHIFT+J is not opening anything with me...

i am running a Macbook Pro with french keyboard fyi.

Can you explain me the exact process for juts reordering the columns, 
then save the order selected and apply it to the mailbox ?
this is just to make sure i am doing the right things.

Also, if you can propose another option to open the error console...

Thanks
Franz

**Comment by micz** [comment]
Please try COMMAND+OPTION+J or in the "Tool menu", under "Develpoper tools", the "Error console".

To apply in the mailbox, just use the "Save columns as CW default" in the folder that has the right columns setup, then use the "Reset columns to CW default" in the folder with the wrong columns setup.

**Comment by micz** [comment]
Issue closed, feel free to open it again if needed.
