### ISSUE TITLE
CW Header Edit doesn't work for ID's with a single letter

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#69]
# Works

## Single number
* ID: 1
* Mail Header: 1
* Column Name: ID with a single number
* Tooltip: ID with a single number
* Advanced: Check "This mail message header can be manually modified."

Try to edit:
* Show the column in the mails
* Click on "CW Header Edit" -- The text is added when I click on OK

## Dual letters
* ID: aa
* Mail Header: aa
* Column Name: ID with dual letters
* Tooltip: ID with dual letters
* Advanced: Check "This mail message header can be manually modified."

Try to edit:
* Show the column in the mails
* Click on "CW Header Edit" -- The text is added when I click on OK

# Single letter doesn't work
Single numbers work as described above so I assume this is a bug.

* ID: a
* Mail Header: a
* Column Name: ID with a single letter
* Tooltip: ID with a single letter
* Advanced: Check "This mail message header can be manually modified."

Try to edit:
* Show the column in the mails
* Click on "CW Header Edit" -- The text is **not** added when I click on OK

**Comment by micz** [comment]
What do you mean with "doesn't work"?
I added these three kinds of custom columns without any problem.

**Comment by davidhedlund** [comment]
I updated the issue by providing more steps.

**Comment by micz** [comment]
I can't replicate the problem. In my installation all is correctly saved.
May you post your logs, as described here: https://github.com/micz/ColumnsWizard/issues/59#issuecomment-369052186 ?
Thank you.

**Comment by davidhedlund** [comment]
We're lucky, I could not reproduce this issue in a (yet another) fresh profile.

**Comment by micz** [comment]
Ok, thank you.
