### ISSUE TITLE
Comment issue on #52

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#70]
I cannot add comments in https://github.com/micz/ColumnsWizard/issues/52 with my user davidhedlund, not even from a fresh browser profile. My friend flyingzebras could comment though.

This is so weird. Can you please have a look?

**Comment by micz** [comment]
I see nothing different on that issue than any other. What error do you see?

**Comment by davidhedlund** [comment]
No error at all. The "Leave comment" field is blanked when I hit the Comment button as it is supposed to but not text is posted.

**Comment by micz** [comment]
I'm sorry I can't help you, maybe you could contact the github support.

**Comment by davidhedlund** [comment]
Yes, I emailed them. Thanks.

**Comment by davidhedlund** [comment]
My "friend" flyingzebras is my secret account. What I wanted to comment on https://github.com/micz/ColumnsWizard/issues/52 was this:

> Can you please add this issue to the 6.1 milestone. I submitted this issue two and half years ago from the wrong user account. I really need this feature, so if it's feasible please try to fix it.

 I will delete this comment.

**Comment by davidhedlund** [comment]
Is it hard to solve that issue?

**Comment by davidhedlund** [comment]
Test

**Comment by davidhedlund** [comment]
I emailed the the comment issue on https://github.com/micz/ColumnsWizard/issues/52 with specific details to the GitHub staff and this is what they responded:

> If the issue that you're experiencing occurs only with a specific repository or issue page, this is typically not the result of any technical issue, but may be a result of configurations or settings performed by another user.
> 
> We do consider these types of actions confidential, and so I'm afraid we won't be able to share any details beyond this

**Comment by micz** [comment]
I did nothing on that issue. If you forward to m@micz.it their answer, I'll email them directly.

**Comment by davidhedlund** [comment]
> If you forward to m@micz.it their answer, I'll email them directly.

Done.

**Comment by micz** [comment]
I wrote to github support.
