### ISSUE TITLE
Value not shown in mail list

### ISSUE THREAD

**Issue by readonly24** [micz/ColumnsWizard#73]
Hi, I have created a special column called "X-PO". I can edit it, and the new header is written into the mails header. Also I can search (and find) the text using Ctrl-Shift-F, but the text is not shown in the X-PO-column of the mail list. Can you please help?

Tested with CW 6.1, Thunderbird 38.7.2 and 52.9.0

![xpo](https://user-images.githubusercontent.com/36458356/42434208-8bf26110-8352-11e8-9b61-39bf171f2786.png)

**Comment by readonly24** [comment]
I add another screenshot, maybe this makes it more clear.

![1](https://user-images.githubusercontent.com/36458356/42692057-9cfdda24-86aa-11e8-8d5d-6bc26e5d9503.png)

**Comment by readonly24** [comment]
Can someone help, please?

**Comment by readonly24** [comment]
Anybody here or is this extension abandoned?

**Comment by micz** [comment]
In a test folder, may you try to rebuild the index of the folder?
If you open the error console (CRT+SHIFT+J) there are any error messages?

**Comment by readonly24** [comment]
Hello micz,

thanks for your help. Rebuilding the index does not help, the error console showns nothing related to ColumnsWizard.

But I respect your descission to suspend the addon developemt, so you don't have to spend any time on this issue.

**Comment by vrillusions** [comment]
In case this helps you or anyone else I was having a similar issue.  For me the header was `X-VR-SCORE`.  When added like that it didn't display.  I then recreated the custom column as `x-vr-score` (all lowercase).  I read somewhere that internally the values are stored all lowercase.  So my guess is it was trying to show `X-VR-SCORE` which didn't exist but `x-vr-score` does.

**Comment by cleidigh** [comment]
@readonly24 
@vrillusions 
We are not suspended !  We are alive and moving forward 👍

**Comment by micz** [comment]
@cleidigh May you force to be saved as lowercase the "Mail Header Field" in the custom column editor?

![image](https://user-images.githubusercontent.com/61795/91359175-53ab6780-e7f4-11ea-818a-910fa989b261.png)

**Comment by cleidigh** [comment]
@micz 
I am bit confused.  it looks like at some point you commented out toLowercase for header
I restored that quote and it now , but I cannot really test it.  I cannot figure out how to set
the custom header for an outgoing e-mail.  I tried saving a new e-mail with the header as a draft
then sending it but it arrives without the header.
If you think that b17 is correct on this I will cleanup and Release.
https://github.com/micz/ColumnsWizard/blob/v7.0.0/xpi/columnswizard-7.0.0-b17-tb.xpi
Christopher

```
						if (document.getElementById("ColumnsWizard.dbHeader").value.match(re_dbh) !== null) {
							newcol.dbHeader = document.getElementById("ColumnsWizard.dbHeader").value.match(re_dbh).join('').replace(':', '').toLowerCase();
						} else {
							newcol.dbHeader = document.getElementById("ColumnsWizard.dbHeader").value.toLowerCase();
						}

```

**Comment by micz** [comment]
@cleidigh I tested b17 and the lowercase is working. I close this issue. Thanks.
