### ISSUE TITLE
Volunteer for added owner to continue updating ColumnsWizard?

### ISSUE THREAD

**Issue by cleidigh** [micz/ColumnsWizard#74]
@micz 
Hello !  I have enjoyed using your add-on for sometime.  I am working to help update various add-ons to continue the great Thunderbird.

Would you like to add me as an owner so I could continue to update your add-on?  I could also clone and continue it with a modified ID.  

Thanks.
Christopher

**Comment by micz** [comment]
Dear Christopher,

I would be pleased to let you help me with this addon, may you reach me at m@micz.it?
Thank you!

Mic
