### ISSUE TITLE
Doesn't work in Thunderbird 68.0

### ISSUE THREAD

**Issue by BillH99999** [micz/ColumnsWizard#85]
The extension does not appear to work in Thunderbird 68.0.  Is there any plan to update it so it will work?

Thanks,
Bill

**Comment by SergeLalonde** [comment]
Is there any chance that this add-on will be updated for version 68.*?

**Comment by davidhedlund** [comment]
https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/versions/?page=1#version-6.1.2
* Doesn't work with 68.0 when I tested it.
* Worked with 60.9.1 (this is the next stable version after version 68.0) when I tested it.

I think you want to modify [manifest.json](https://github.com/micz/ColumnsWizard/blob/master/src/manifest.json)

> "strict_max_version": "61.0"

to

> "strict_max_version": "60.9.1"

and re-upload https://addons.thunderbird.net/thunderbird/downloads/file/1012459/columnswizard-6.1.2-tb.xpi

**Comment by davidhedlund** [comment]
https://github.com/micz/ColumnsWizard/issues/87

**Comment by davidhedlund** [comment]
This issue is a duplication of: [Convert ColumnsWizard to a WebExtension to support Thunderbird 68](https://github.com/micz/ColumnsWizard/issues/61)

Can you please close it?

**Comment by cleidigh** [comment]
@BillH99999 
@davidhedlund 
@SergeLalonde 
@micz 

I am now going full bore on this as well as positioning for 78 !
Track  status in #90 
Also , I have b2 minimally working
https://github.com/micz/ColumnsWizard/tree/v7.0.0/xpi
Grab the latest 7.0.0-bx

Christopher

**Comment by cleidigh** [comment]
it's released!
