### ISSUE TITLE
Not working with 68.1.2

### ISSUE THREAD

**Issue by kanlukasz** [micz/ColumnsWizard#87]
Not working with 68.1.2

**Comment by SergeLalonde** [comment]
Is there any chance that this add-on will be updated for version 68.*?

**Comment by alphatonic** [comment]
Yes, please update this awesome add-on. Thunderbird is kinda crappy without it.

**Comment by davidhedlund** [comment]
https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/versions/?page=1#version-6.1.2
* Doesn't work with 68.0 when I tested it.
* Worked with 60.9.1 (this is the next stable version after version 68.0) when I tested it.

I think you want to modify [manifest.json](https://github.com/micz/ColumnsWizard/blob/master/src/manifest.json)

> "strict_max_version": "61.0"

to

> "strict_max_version": "60.9.1"

and re-upload https://addons.thunderbird.net/thunderbird/downloads/file/1012459/columnswizard-6.1.2-tb.xpi

**Comment by davidhedlund** [comment]
https://github.com/micz/ColumnsWizard/issues/85

**Comment by davidhedlund** [comment]
https://github.com/micz/ColumnsWizard/issues/89

**Comment by kanlukasz** [comment]
I saw this but it's all chaotic and I'm confused.
Is it finally know whether it will work or not?

To be honest, I haven't seen any author activity for a long time
Probably it's another great but dead project

**Comment by cleidigh** [comment]
@kanlukasz 
@alphatonic 
I am now going full bore on this as well as positioning for 78 !
Track  status in #90 
Also , I have b2 minimally working
https://github.com/micz/ColumnsWizard/tree/v7.0.0/xpi
Grab the latest 7.0.0-bx

Christopher

**Comment by davidhedlund** [comment]
@cleidigh Thank you for your hard work!!

When will it appear on AMO?

**Comment by twoatechguy** [comment]
> When will it appear on AMO?

I appreciate the hard work too, but since it's in beta and doesn't work to define or edit columns, it's premature to have it on the addons site.

**Comment by cleidigh** [comment]
@twoatechguy  you are correct, I will only posted on AMO once it's ready.
While it is currently b2 it's working progress .
I will post a status in #90 and describes a current level of usage for those who want to test and/or use early.
@cleidigh

**Comment by cleidigh** [comment]
All::
Final Beta b14 is ready for testing
Please follow/help with #91 
Thanks
Christopher

**Comment by cleidigh** [comment]
@davidhedlund 
@alphatonic 
@kanlukasz 
@SergeLalonde 
All
It's officially released!
thanks for all your patience
cheers
Christopher
https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/?src=userprofile

**Comment by davidhedlund** [comment]
Thank you once again, for the final release!

**Comment by cleidigh** [comment]
@davidhedlund 
ThanksForTheSupport!
let me know if you see any issues, lots of changes...
Christopher
