### ISSUE TITLE
CW seems to forget custom columns after some days

### ISSUE THREAD

**Issue by aostlender** [micz/ColumnsWizard#88]
regularly folders customized with CW forget their columns and restore to firefox defaults.
This happens after a period of some days with folders in maildir and in mbox format.
I do not have the expertise to give more facts / information. Sorry for that. 
Any help is welcome.
Please ask if any further info is requested.
CU 
Andreas

**Comment by cleidigh** [comment]
@aostlender 
just-released v7.0.0
many changes for 68 that may fix this
if you can check check out
it is now listed
https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/?src=userprofile
Christopher

**Comment by aostlender** [comment]
thanks a lot
i will try ;)
