### ISSUE TITLE
CW 6.1.2: Incorrect strict_max_version

### ISSUE THREAD

**Issue by davidhedlund** [micz/ColumnsWizard#89]
https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/versions/?page=1#version-6.1.2
* Doesn't work with 68.0 when I tested it.
* Worked with 60.9.1 (this is the next stable version after version 68.0) when I tested it.

I think you want to modify [manifest.json](https://github.com/micz/ColumnsWizard/blob/master/src/manifest.json)

> "strict_max_version": "61.0"

to

> "strict_max_version": "60.9.1"

and re-upload https://addons.thunderbird.net/thunderbird/downloads/file/1012459/columnswizard-6.1.2-tb.xpi

**Comment by davidhedlund** [comment]
https://github.com/micz/ColumnsWizard/issues/87

**Comment by twoatechguy** [comment]
Where is there a version 61?  https://www.thunderbird.net/en-US/thunderbird/releases/

**Comment by davidhedlund** [comment]
> Where is there a version 61? https://www.thunderbird.net/en-US/thunderbird/releases/

There is no such version.

**Comment by twoatechguy** [comment]
So where is the concern? Is 60.9.1 < 61?  Yes? Then it works.

**Comment by davidhedlund** [comment]
> So where is the concern? Is 60.9.1 < 61? Yes? Then it works.

Oh sorry you are right. I was tired when I submitted this issue. I think I got confused by the text at https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/versions/?page=1#version-6.1.2:

>  Works with Thunderbird 60.0 and later

**Comment by cleidigh** [comment]
All
working on the next 68 compatible version, I going to punt on any other changes the moment.
closing unless I am missing something?
Christopher
