### ISSUE TITLE
v7.0.0 Release Tasks & Status

### ISSUE THREAD

**Issue by cleidigh** [micz/ColumnsWizard#90]
Current Beta:  https://github.com/micz/ColumnsWizard/blob/v7.0.0/xpi/columnswizard-7.0.0-b18-tb.xpi
Release: v7.0.0

Status:
- sort type/ order preference - Fixed!
- header Editor - fixed - including submenus
- All locales + Japanese  Spanish
- functionally complete

Current Work:

- track beta new problems
- cleanup Debug
- cleanup UI

Initial Fixup Tasks:

- [x] - Update module imports - var { x } =
- [x] - Update Columns menu format / update functions
- [x] - Fixup menu functions/check updated
- [x] - Fixup styling/dialogue for options temporarily
- [x] - Temp preferences fix

Main Conversion Tasks:

- [x] - Id/create/modify deprecated & other XUL elements => HTML/CSS
- [x] - Tab Widget
- [x] - Checkbox
- [x] - Radio
- [x] - Button
- [x] - List
- [x] - Prototype before merge
- [x] - Create base options page
- [x] - Tab navigation
- [x] - implement defaultColList - base
- [x] - implement custom list
- [x] - complete lists (auto 

Cleanup/Release Tasks:
- [x] - get testing help for b14

**Comment by PissedFirefoxUser** [comment]
Chris,
Tested b10, found NO flaws! It looks good to go! 
1) I created a new test folder, test folder1.
2) I dragged existing columns around and set as new CW default.
3) Created test folder2.
4) Confirmed test folder2 was created exactly as per my new CW default.
5) I dragged folders around in test folder2.
6) I reset columns in test folder2 back to existing CW default.
7) Went back to test folder1 and dragged columns back to the way I really want them and set as new CW default.
8) Went back to test folder2 and reset to CW default. Columns reset instantly to my preferred default.
All worked to perfection.
All UI open and respond with no issues.
Congratulations, and THANK YOU!

For future development (and added sophistication:
Allow the creation of three CW default configurations: one for new subfolders, one just for the Inbox, and one just for the Sent folder.
Justification: Inbox must have the From column enabled always and should probably always have the Junk button column enabled too, but this column is not needed in any other folder; the Sent column doesn't need the From column (I know I sent the email).
-a.l.

**Comment by cleidigh** [comment]
@PissedFirefoxUser 
excellent!  that bug annoyed me.
still have a lot to go for the remaining features, however, I think the core functionality
is quite usable.  
have to get each of the lists to cross update, current the recently enabled custom entries
don't show up in the default list without closing/reopening 
have to convert the other parts of the UI
and lots of cleanup
the new feature you mentioned makes sense, I actually was thinking about that week ago
just have to figure out the time!
Christopher

**Comment by cleidigh** [comment]
All
We are released!
