### ISSUE TITLE
ColumnsWizard for TB68  v7.0.0-b18 Beta testing

### ISSUE THREAD

**Issue by cleidigh** [micz/ColumnsWizard#91]
I know it's taken longer than I would have Liked...

Now some testing help would be great, b14 is functionally complete , localized (including the new Japanese locale)
I will get this released this  as soon as I get Decent Feedback

All:  Any testing help would be great especially non- Windows platforms.
If you do not have time I totally understand, hoping to release a few days.

https://github.com/micz/ColumnsWizard/blob/v7.0.0/xpi/columnswizard-7.0.0-b14-tb.xpi
@cleidigh

**Comment by micz** [comment]
I tested b14 and sent you an email with a few notes.
Thank you for your work!

**Comment by kanlukasz** [comment]
I'm starting to test.
Is it possible to create a column containing the original recipient/sender email address ?
I mean pure email address, not "friendly name"

**Comment by micz** [comment]
@kanlukasz It's possible to create a custom column only if there is a mail header with that information. In this case the from/to field contains the complete "name + address".
So I think it's not possible without adding a new hardcoded column that stores only the address.

**Comment by cleidigh** [comment]
Current Issues:
- Custom columns missing from header editor-regression
- Tab title tooltips require creative CSS - currently a challenge

**Comment by paulcrown** [comment]
I'm not sure what I am missing.  I am on Ubuntu 18.04.5, TB 68.10.0 64-bit.  Everything is working, except: the column contents in the message list are blank.  I have tried b14 and b15.

I love the concept of the addon.  Can you point me in the right direction to what may be missing?

Thanks.

![custom-column](https://user-images.githubusercontent.com/8922235/91243103-c510ea80-e70e-11ea-8741-a920e181b585.png)
![new-column](https://user-images.githubusercontent.com/8922235/91243105-c5a98100-e70e-11ea-9c2e-ff55ba71b481.png)
![header-set](https://user-images.githubusercontent.com/8922235/91243113-cb9f6200-e70e-11ea-9ffe-2f40b0f306cc.png)
![empty-column](https://user-images.githubusercontent.com/8922235/91243114-ce01bc00-e70e-11ea-98e3-6c2788dc5a87.png)

**Comment by cleidigh** [comment]
@paulcrown 
I have to be honest I have not had a chance to do testing off Windows.
Thanks for the post and testing.
I doubt that it will solve the problem but I just posted b16
https://github.com/micz/ColumnsWizard/blob/v7.0.0/xpi/columnswizard-7.0.0-b16-tb.xpi
it is possible that it will fix the issue, however, I may suggest
starting with default preferences in case there were any preference errors.
I will also do some testing my Mint VM.
Christopher

**Comment by micz** [comment]
@paulcrown If everything works fine, the new column is filled for new messages received after the new configuration has been done (this is how Thunderbird works). You can force Thunderbird to fill that column using the "repair folder" function that forces Thunderbird to rebuild the index for that folder.
I suggest to test that function on a test profile or a small folder, because I don't know how it could impact other addons you may have.

**Comment by cleidigh** [comment]
@micz 
Did I finally get your menu Working ?

**Comment by micz** [comment]
> @micz
> Did I finally get your menu Working ?

The menus are working! 👍 
I tested with success also:
- New folder default
- Header editing
- Saving and restoring the CW default columns
- Editing a custom column (also with the Mail Header Editor tab)

You're doing a great job! Thank you!! 🥇

**Comment by paulcrown** [comment]
@cleidigh The error console shows your debug messages, but I don't see any errors.  

![debug-console](https://user-images.githubusercontent.com/8922235/91356915-05777380-e7b6-11ea-83cb-581d22bac0a0.png)

@micz I found the Repair Folder option and tried it without any change (it looks like it deleted the .msf file and rebuilt it).  I am adding the custom header at the mailserver, so all new emails have the custom header and "xxx" listed.  I show all headers, and X-Cust-Name is included and set to xxx.  The column shows in the message list with 'Client Name' title, but the column itself remains empty.

**Comment by micz** [comment]
@paulcrown maybe this is the issue: https://github.com/micz/ColumnsWizard/issues/73#issuecomment-429519357

Also, I'm sorry I gave you a wrong advice, it's not the folder repair, but you need to force Thunderbird recreate the Global Index as described here: https://support.mozilla.org/en-US/kb/rebuilding-global-database
Try this option only if you're confident in what you are doing, because you could damage your data. Do always a backup before.
This is not needed to check if the lowercase fixes the problem, just send to yourself a new email with that header.

**Comment by paulcrown** [comment]
@micz The lowercase issue was the problem.  I did not realize that lowercase was required in the Custom Header definition.  I deleted my old definition in the column editor; added a new one with all lowercase for the Mail Header field, and immediately switched over to the message list with the column fully populated.  Thanks.

@cleidigh b16 all works fine on Ubuntu 18.04.5, TB 68.10.0 64-bit.

**Comment by cleidigh** [comment]
@paulcrown 
Excellent!!
@micz  indicated the lowercase might be the issue, but I have to clarify what is correct, should I convert all the headers lowercase if so how do I make sure Thunderbird does not expect uppercase?

**Comment by micz** [comment]
@cleidigh I understood that Thunderbird is saving internally that header lowercase, so it needed to save that definition lowercase, otherwise the column is not populated.
I think it has to be fixed here https://github.com/micz/ColumnsWizard/blob/master/src/chrome/content/mzcw-settings-customcolseditor.js#L125

**Comment by micz** [comment]
@cleidigh the dbHeader is saved lowercase internally by Thunderbird.
It has to be fixed here: https://github.com/micz/ColumnsWizard/blob/v7.0.0/src/chrome/content/mzcw-settings-customcolseditor.js#L133
It has to be checked why that toLowerCase seems to not be working.
I added the bug label to issue #73.

**Comment by micz** [comment]
@cleidigh b17 is working in regard to #73.

I found a bug when adding a new custom column.
When I add a custom column, the new column is added at the end of the list. If I select that column and click on the edit button, an empty new column dialog is opened.

It also happened twice that, clicking on a column and then on the edit button, nothing opens, but I was not able to recreate the problem.
I saved the log once:

```
Target <td class="index">testm2</td> mzcw-customcolslist.jsm:331:11
9 mzcw-customcolslist.jsm:336:11
Array(16) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
mzcw-customcolslist.jsm:337:11
Object { _values: {…}, found: false, filtered: false, values: values(), show: show(), hide: hide(), matching: matching(), visible: visible(), elm: tr.list-row.id.selected-row }
mzcw-customcolslist.jsm:339:11
SelectedRow: list.controller2.js:76:11
<tr class="selected-row" height="20px">
                  <th class="enabled_th" data-tooltip="Enabled">
                    <div class="ctooltip" data-tooltip="Enabled"></div>

                    <img src="chrome://columnswizard/skin/checked-box-64px.png" width="22px" height="22px">
                      
                    </th>
                  <th class="searchable_th">
                    <div class="ctooltip" data-tooltip="Searchable"></div>
                    <img src="chrome://columnswizard/skin/search-64px.png" title="Searchable" width="18px" height="18px">
                  </th>
                  <th class="header-id" height="20px">ID</th>
                  <th class="mail-header" height="20px">Mail Header</th>
                  <th class="col-name" height="20px">Column Name</th>
                  <th class="tooltip" height="20px">Tooltip</th>
                </tr> list.controller2.js:77:11
null list.controller2.js:80:12
null settings.js:226:11
no select settings.js:228:12
```

**Comment by micz** [comment]
b17 download link: https://github.com/micz/ColumnsWizard/blob/v7.0.0/xpi/columnswizard-7.0.0-b17-tb.xpi

**Comment by cleidigh** [comment]
@micz 2 
that is another reoccurring issue, next effort
Whenever you have a chance, if you can describe how to send an e-mail with custom headers that would help me for testing.

**Comment by micz** [comment]
@cleidigh I added a wiki page with some instruction: https://github.com/micz/ColumnsWizard/wiki/Custom-Column-Header-Editor-Testing
Let me know if this is enough.

**Comment by cleidigh** [comment]
@micz 
I think I finally got the indexing and syncing for the Edit/Delete issues , but I did b18 just before crashing so I did not test a lot but I think sufficiently.  I will try to get them focused row in view next.
https://github.com/micz/ColumnsWizard/blob/v7.0.0/xpi/columnswizard-7.0.0-b18-tb.xpi
Christopher

**Comment by micz** [comment]
Ok, the list works in b18, great!!

**Comment by cleidigh** [comment]
Awesome
I am cleaning up and releasing
Also we have 16 locales now

**Comment by cleidigh** [comment]
@micz 
@paulcrown 
@BillH99999 
@kanlukasz 

I have posted v7.0.0 for review!  the queue was almost empty so we they get approved quickly.
Thanks to everyone that you help testing, etc.
Cheers
Christopher

**Comment by BillH99999** [comment]
Thank you for updating the plugin and all the hard work you put into it.

Bill
