### ISSUE TITLE
Config screen and columns no longer available

### ISSUE THREAD

**Issue by emja** [micz/ColumnsWizard#93]
TB 60.8.0 (64-bit)
CW 7.0.0

Subsequent to latest update of CW the defined columns have disappeared and the config screen is no longer available.

I've removed and reinstalled CW, no success.

**Comment by cleidigh** [comment]
@emja 

I have to check out 60 I may have missed compatibility issue
I may not be able to make it compatible with both
I did not add any new features just UI changes
60 is now 2 releases behind.  it's very hard to make things compatible
with the major changes going onk

if you don't mind me asking, what is blocking you from upgrading to 68?

**Comment by emja** [comment]
ok, that's fair.

I'd pinned at v60 because of a problem with another add-on. I don't remember the details, or even if it's still a legitimate issue, so I'll try upgrading to v68 and see how I go.

Thanks!

**Comment by emja** [comment]
Righto, successfully upgraded to 68, and all addons work incl ColumnsWizard (most importantly!).

cheers!
