### ISSUE TITLE
Is ColumnsWizard dead?

### ISSUE THREAD

**Issue by BillH99999** [micz/ColumnsWizard#98]
Christopher,

I notice that nothing has happened with ColumnsWizard since beta 6 was released last December.  Is it dead?  Or, are there plans to update it for TB 91 at some point?

Thanks,
Bill

**Comment by jh20001** [comment]
Sadly, this seems to be the case. I finally deleted the plugin, assuming it won't be coming back. I can't even remember what I needed it for anymore, so that was the final nail in the coffin for me. If I can't remember, it must no longer be a "need"? *shrug* :)

**Comment by BillH99999** [comment]
I know for me the most useful feature was that you could save your column layout and set it so that any newly created folder or subfolder would use that column layout rather than the TB default.  Sadly it does look like this add-on is dead.  :(

**Comment by SergeLalonde** [comment]
For me, it was the only way to add the Reply-To column for some emails that are sent by an automated email server proxy. I haven't found anything that can do that. :-(

**Comment by jh20001** [comment]
Ah yes! Now I remember why I was using it. Changing the default order and such. That's right! lol. Oh well :(

**Comment by Ircama** [comment]
For me, the most important element of this plugin is the possibility to add the CC column to the Inbox and to the other windows (e.g., Sent Items). Currently, Thunderbird forces users to open each email, one by one, to check the CC recipients (and this is also a field that cannot be used for quick ordering).
It is quite weird that the standard column selector of Thunderbird does not have the CC field among the selectable items and requires the development of a plugin to get it. Does someone know whether there is a way (e.g., somewhere in the profile) to customize Thunderbird to get this field?

**Comment by micz** [comment]
I'm sorry, too much is changed in the new versions of Thunderbird that I don't even know if is still possibile to do what this extension did.
